# Generated by Django 5.0.8 on 2024-10-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categorymodel",
            old_name="categ_name",
            new_name="name",
        ),
    ]
