# Generated by Django 5.0.8 on 2024-10-20 10:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_rename_categ_name_categorymodel_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="coursemodel",
            name="rating",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="coursemodel",
            name="times_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coursemodel",
            name="times_viewed",
            field=models.IntegerField(default=0),
        ),
    ]
